name: Deploy to Replit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Replit
        run: |
          curl -X POST https://replit.com/api/v0/your-repl-id/git-pull -H "Authorization: Bearer ${{ secrets.REPLIT_API_KEY }}"
